name: Hent ferske Avinor-data

on:
  schedule:
    - cron: '*/5 * * * *' # Kjører hvert 5. minutt
  workflow_dispatch: # Gjør at du kan klikke på "Run workflow" manuelt

# Gir roboten de nødvendige rettighetene til å oppdatere GitHub Pages direkte
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  oppdater-data:
    runs-on: ubuntu-latest
    steps:
    - name: Sjekk ut kildekoden
      uses: actions/checkout@v4

    - name: Hent data fra Avinor (Forkledd som nettleser)
      run: |
        # -H legger til en User-Agent slik at Avinor tror en vanlig Chrome-nettleser besøker dem
        curl -H "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36" -s "https://data.avinor.no/flightdata/v1/airport/OSL/arrivals?TimeWindow=1" -o osl.xml
        curl -H "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36" -s "https://data.avinor.no/flightdata/v1/airport/TOS/arrivals?TimeWindow=1" -o tos.xml

    - name: Sett opp GitHub Pages-verktøy
      uses: actions/configure-pages@v4

    - name: Pakk sammen filene (html og xml)
      uses: actions/upload-pages-artifact@v3
      with:
        path: '.' # Pakker alt som ligger i denne mappen

    - name: Send direkte til GitHub Pages live-server
      uses: actions/deploy-pages@v4
